version: 2

models:
  - name: customers
    description: One record per customer
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: Null when no orders are placed ever
  
  - name: stg_customers
    description: cleans customer data
    columns:
      - name: customer_id
        description: primary key
        tests:
          - unique
          - not_null
          
  - name: stg_orders
    description: cleans up order data
    columns:
      - name: order_id
        description: primary key
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values:
                - "placed"
                - "shipped"
                - "completed"
                - "return_pending"
                - "returned"
      - name: customer_id
        tests:
          - not_null
          - relationships:
              field: customer_id
              to: ref('stg_customers')
          
          
          